In [1]:
import numpy as np

In [3]:
num = np.array([56,33,12,78,52,68,25])

In [5]:
num

array([56, 33, 12, 78, 52, 68, 25])

In [7]:
type(num)

numpy.ndarray

In [9]:
print(num)

[56 33 12 78 52 68 25]


In [11]:
num.dtype ##datatype of elements inside array

dtype('int32')

In [13]:
num = np.array([56,33,12,78,52,68,25], dtype = np.int16)

In [15]:
num

array([56, 33, 12, 78, 52, 68, 25], dtype=int16)

In [17]:
num.dtype

dtype('int16')

In [19]:
num[5]

68

In [21]:
num[5] = 61
num

array([56, 33, 12, 78, 52, 61, 25], dtype=int16)

In [29]:
num.ndim

1

In [25]:
num.min()
num.max()

78

In [31]:
##tolist array to list conversion
num.std()

21.204543217462255

In [33]:
num1 = np.array([45,67,23.56,78.25,89.03])

In [35]:
num1.dtype

dtype('float64')

In [37]:
list = num1.tolist()

type(list)

In [43]:
num * 2

array([112,  66,  24, 156, 104, 122,  50], dtype=int16)

In [45]:
list * 2

[45.0, 67.0, 23.56, 78.25, 89.03, 45.0, 67.0, 23.56, 78.25, 89.03]

In [47]:
num > 40

array([ True, False, False,  True,  True,  True, False])

In [49]:
num[num > 40]

array([56, 78, 52, 61], dtype=int16)

### Matrix Operation

In [55]:
M = np.array([[5,6,7],[2,4,3],[6,8,9],[0,1,3]])
M

array([[5, 6, 7],
       [2, 4, 3],
       [6, 8, 9],
       [0, 1, 3]])

In [58]:
M.ndim

2

In [60]:
M.shape  ####dimension ---  Rowa and Column

(4, 3)

In [62]:
M.size ########## How many elements are there

12

In [66]:
M[2,1]

8

In [68]:
M.T

array([[5, 2, 6, 0],
       [6, 4, 8, 1],
       [7, 3, 9, 3]])

In [70]:
M.transpose()

array([[5, 2, 6, 0],
       [6, 4, 8, 1],
       [7, 3, 9, 3]])

In [72]:
M.reshape(6,2)

array([[5, 6],
       [7, 2],
       [4, 3],
       [6, 8],
       [9, 0],
       [1, 3]])

In [74]:
M.flatten()

array([5, 6, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [76]:
M.reshape(-1) ####If no of elements are not known

array([5, 6, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [80]:
M.reshape(-1,4)   ###Rows are adjusted but compulsorily 4 column

array([[5, 6, 7, 2],
       [4, 3, 6, 8],
       [9, 0, 1, 3]])

In [84]:
M.reshape(-1)

array([5, 6, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

### PANDAS

In [ ]:
### load prepare model manipulate analyze
